# Deployment command: docker stack deploy -c postgres.yml postgres
# Use postgres/example user/password credentials

version: "3.1"

services:
  db:
    image: postgres
    container_name: newpostgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: db
    ports:
      - 5432:5432
